Revise Getting Started steps based on recent SDK fixes.
interbit/docs-interbit pull request #15
Opened 2018-09-14 18:03 UTC by btlewan

2018-09-14 20:44 UTC, djlmills requested changes

2018-09-14 20:44 UTC, djlmills commented on getting-started/run.md
>  1.  **Start your application in a new terminal:**
This is a bit like introducing a new ingredient half way through a recipe. Maybe we should state up front, "Open two terminal sessions. In the first terminal... In the second terminal..."

2018-09-17 17:40 UTC, nicholeous approved these changes
:smile_cat:

2018-09-17 18:41 UTC, djlmills approved these changes

2018-09-17 19:45 UTC, merged