Some additional tweaks to the new Covenants coverage.
interbit/docs-interbit pull request #16
Opened 2018-09-18 17:04 UTC by btlewan

2018-09-18 17:13 UTC, nicholeous requested changes

2018-09-18 17:13 UTC, nicholeous commented on key-concepts/covenants.adoc
> +Interbit applications are built on link:https://reactjs.org/[React], they
You can build an Interbit application with anything that will interface with JavaScript. The app need not be React, although we do use React ourselves and give tools to make React development easier with Interbit.

2018-09-18 17:28 UTC, nicholeous approved these changes
:smile_cat:

2018-09-19 17:37 UTC, merged

2018-09-19 17:37 UTC, mgbarber reviewed
Looks good. Thanks.